<div class="container">
    <form method='POST' action="/magento2/praccus/index/setpassword">
        <div class="form-group">
            <label for="phone">Your new password</label>
            <input type="password" class="form-control" id="password" placeholder="Enter your new password" name="password">
        </div>
        <button type="submit" class="btn btn-primary" name="submitbtn" value="<?=$block->getCustomerId()?>">Submit</button>
    </form>
</div>
